name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/output/metrics.classic.svg
          user: P4ST4S
          token: ${{ secrets.METRICS_TOKEN }}
          # Base metrics
          base: header, activity, community, repositories, metadata
          # Popular plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_topics: yes
          plugin_followup: yes
